### ISSUE TITLE
Custom sqlite3 path

### ISSUE THREAD

**Issue by tadfisher** [cireu/emacsql-sqlite3#10]
I would like to tell this package where the `sqlite3` binary is located, rather than relying on `executable-find`. This is mainly to enable reproducible builds in NixOS.

Can there be an `emacsql-sqlite3-executable` variable that could be set, using `executable-find` as a fallback?

**Comment by cireu** [comment]
Of course! I' m also a user of NixOS. :)

**Comment by cireu** [comment]
Just pushed a commit to achieve this goal, You can use `emacsql-sqlite3-executable` if everything is OK.

**Comment by tadfisher** [comment]
Thank you!
