### ISSUE TITLE
Releasing on melpa-stable

### ISSUE THREAD

**Issue by 4lex1v** [cireu/emacsql-sqlite3#14]
Hi!
Any chance you could make a release on melpa-stable? It's the only dependency that's missing on stable to get org-roam - https://stable.melpa.org/#/org-roam.

**Comment by cireu** [comment]
Release tag added: https://github.com/cireu/emacsql-sqlite3/releases/tag/1.0.0

**Comment by cireu** [comment]
God damn! I tag release on an older commit. Please use tag 1.0.1 https://github.com/cireu/emacsql-sqlite3/releases/tag/1.0.1(current master)

**Comment by 4lex1v** [comment]
Thank you for such a fast response, appreciate it!
