### ISSUE TITLE
Needs update for SQLite 3.38.0

### ISSUE THREAD

**Issue by spwhitton** [cireu/emacsql-sqlite3#36]
As reported in [Debian's bug tracker](https://bugs.debian.org/1006666), emacsql-parse needs an update for SQLIte 3.38.0.  If an attempt is made to create a table that already exists, the program now outputs "Parse error:" not just "Error:".

**Comment by cireu** [comment]
I've pushed some changes on master, but the CI cannot cover the SQLite 3.38.0. If you still have some problem, feel free to reopen it.

**Comment by spwhitton** [comment]
Thanks!

On Fri 04 Mar 2022 at 02:15am -08, Zhu Zihao wrote:

> I've pushed some changes on master, but the CI cannot cover the SQLite 3.38.0. If you still have some problem, feel free to reopen it.

-- 
Sean Whitton
