### ISSUE TITLE
Depreate this package in favor of the new builtin and module backends

### ISSUE THREAD

**Issue by tarsius** [cireu/emacsql-sqlite3#38]
As mentioned at https://github.com/magit/emacsql/issues/113, EmacSQL 4.0.0 will come with two new backends and it automatically picks the best available backend. I recommend that package authors just rely on EmacSQL to pick the backend and not even give users an option to use another.

The package of this package mentions that it doesn't need a compiler. Is that the only reason for it to exist? I believe to remember that this was created to deal with performance issues of `emacsql-sqlite`.

In any case, if EmacSQL cannot use the new `emacsql-sqlite-builtin` backend because Emacs < 29 is used or 29 has been compiled without support for SQLite, then the new module backend or the old custom binary backend are used. And those require a compiler.

Despite that, I think it is time to deprecate this package and remove it from Melpa. This will cause issues for users who now have to figure out how to install a compiler, but it will also prevent other issues that are the result of this not really fitting into the upcoming EmacSQL 4.0.0 anymore.

If you agree, I can take care of removing it from Melpa.

**Comment by cireu** [comment]
> Is that the only reason for it to exist?

Yes, I create this because it's annoying to compile the sqlite binary on Windows.

> If you agree, I can take care of removing it from Melpa.

Agree :+1: , thanks for your help! Maybe make this repo archived later

**Comment by tarsius** [comment]
Done. Cheers!
