### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by mihaiolteanu** [cireu/emacsql-sqlite3#9]
Please add some documentation on the README page on how to use this package, what it offers, what's different from the other packages that offer similar functionality, etc.

This package might be good, or might be not, but nobody ain't gonna have time to test them all and try to figure out on their own all the gotchas and how to set it all up. The result is usually "press the tab's little 'x'".

Thank you,
Mihai

**Comment by cireu** [comment]
Thanks for your attention.

I made a brief description of this package when I was considering to submit it to melpa. 

In general, This package is a backend of [EmacSQL](https://github.com/skeeto/emacsql). A high level Elisp RDBMS frontend. It means that you can use function `emacsql-sqlite3` to create a DB instance, then control it via the interface of  `emacsql`.

For Emacs users, my suggestion is: **If you don't know why you need this, you probably don't need this.** This package won't provide any feature for your convenience. For package developers using `emacsql`, you can choose this package or [emacsql-sqlite3](https://github.com/skeeto/emacsql/blob/master/emacsql-sqlite.el) as an adaptor between sqlite database and high-level interface. They should be fully compatible.

**Comment by cireu** [comment]
https://github.com/cireu/emacsql-sqlite3/commit/998ba547bd14c7406ab5d59820ef140c1819784e should clarify the purpose of this package. You can read it on Github or in `Commentary` section of the elisp file.
